version: '2.3'
services:
  chrome:
    image: selenium/standalone-chrome:3.12

  testing:
    image: b13gmbh/php-builder:7.4
    user: ${HOST_UID}
    links:
      - chrome
    volumes:
      - ${ROOT_DIR}:/testing
    command: >
      /bin/sh -c "
      cd /testing;
      composer install;
      php vendor/bin/codecept run --steps
      "