#!/bin/bash
mkdir .Build
cd .Build
wget https://raw.githubusercontent.com/akiessling/dpool-devops/main/docker-compose.yml
wget https://raw.githubusercontent.com/akiessling/dpool-devops/main/runTests.sh
cd ../
rm composer.json
rm composer.lock
wget https://raw.githubusercontent.com/akiessling/dpool-devops/main/composer.json
wget https://raw.githubusercontent.com/akiessling/dpool-devops/main/composer.lock
sh .Build/runTests.sh
