composer:
  tags: [docker]
  stage: build
  only:
    - test
    - production
  script:
    - bash <(curl -s https://raw.githubusercontent.com/dpool/test-base/main/Job/Script/job.composer.script.bash)
  artifacts:
    expire_in: 60 minutes
    paths:
      - .Build